# Generated by Django 3.1 on 2024-07-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20240719_1517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_appliances',
        ),
    ]
