# Generated by Django 3.1 on 2024-07-19 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_appliances'),
        ('store', '0006_product_appliances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_appliances',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category_appliances'),
        ),
    ]
