# Generated by Django 3.1 on 2024-07-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20240719_1517'),
        ('category', '0002_category_appliances'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category_appliances',
        ),
    ]
